### ISSUE TITLE
Internet Explorer 8 and Strophe.Builder.cnode error

### ISSUE THREAD

**Issue by ivanstojic** [metajack/strophejs#15] opened 2010-12-08 12:32 UTC
Internet Explorer 8 (full version 8.0.7600.16385) reports a "wrong number of arguments" in Strophe.Builder.cnode function, on line 1361 of the built strophe.js file. That corresponds to this line:

var newElem = xmlGen.importNode ? xmlGen.importNode(elem, true) : Strophe.copyElement(elem);

Commenting out the xmlGen.importNode invocation and just going with Strophe.copyElement fixes the problem.

I'm not sure of the implications, but it doesn't work for me the way it is now, and I'm using a version with the ternary operator removed. I can send a pull request with the patch if anyone is interested.

Sincerely,
Ivan

**Comment by ivanstojic** [comment] 2010-12-08 12:33
Ah, also... this bug exists in both the current git master and the version downloadable from the Strophe website.

**Comment by brendon-codes** [comment] 2010-12-08 20:53
This could possibly be related to @vog's patch here: https://github.com/metajack/strophejs/pull/12

I will try to have a look into this within about 5 - 6 days from now.

**Comment by ivanstojic** [comment] 2010-12-10 22:59
Yup, definitely looks related. I'm using the patched version for now and I'm keeping an eye here to see how this resolves.

Good luck and thanks for your work - but you'll also be seeing bug reports from me on some plugins code :-]

**Comment by brendon-codes** [comment] 2010-12-18 01:18
@ivanstojic, are you on Windows 7 or XP?

**Comment by ivanstojic** [comment] 2010-12-18 11:51
The bug I reported was on Windows 7.

**Comment by brendon-codes** [comment] 2010-12-19 01:24
Unfortunately I only have Windows XP + IE8, of which I am not getting this error. This will probably have to be addressed by somebody with access to Windows 7, as I probably won't be getting a copy for another few weeks.

**Comment by vojtajina** [comment] 2011-01-10 16:49
Anything new to that issue ?
vog's patch has already been merged into master, but it doesn't fix the problem for all IEs...
I have tested latest master on XP with IE 8.0 and still got the error `Wrong number of arguments or invalid property assignment`

This could be helpful http://www.alistapart.com/articles/crossbrowserscripting

**Comment by thaBongo** [comment] 2011-01-13 23:20
This works for me in IE8 on Win Server 2008 (note the extra try catch):

```
cnode: function (elem)
{
    var xmlGen = Strophe.xmlGenerator();
    var useXMLGen = false;
    try {
        useXMLGen = xmlGen.importNode!=null;
    } 
    catch (e){
        useXMLGen=false;
    }
    var newElem = useXMLGen ? xmlGen.importNode(elem, true) : Strophe.copyElement(elem);
    this.node.appendChild(newElem);
    this.node = newElem;
    return this;
},
```

**Comment by plievone** [comment] 2011-01-16 13:11
I can confirm this critical bug. On Windows 7 + IE8 the current code gives `TypeError: Wrong number of arguments or invalid property assignment`, and Strophe does not work at all:
    var newElem = xmlGen.importNode ? xmlGen.importNode(elem, true) : Strophe.copyElement(elem);

Surprisingly, the almost equivalent code:
    var newElem;
    try {
      newElem = xmlGen.importNode(elem, true);
    } catch(e) {
      newElem = Strophe.copyElement(elem);
    }
succeeds without stepping into catch block (on Win7 + IE 8, Chrome 8, Firefox 3.6 and Safari 5). 

EDIT: As a fairly common boolean existence check raises an error but calling with correct parameters is ok, perhaps there's a bug in Javascript bindings to the native importNode function on some Windows/IE platforms. I don't know about the speed implications of this extra try...catch block here, unfortunately.

**Comment by micaherne** [comment] 2011-01-20 12:18
plievone's code fixes this for me Windows Vista + IE8 (latest Strophe from git).

**Comment by guperrot** [comment] 2011-02-25 10:25
I'm also using plievone's patch on IE8 (windows 7) and it's working great.

**Comment by becoded** [comment] 2011-03-03 14:37
You just need to change (arround line 1367 in strophe.js)

```
var newElem = xmlGen.importNode ? xmlGen.importNode(elem, true) : Strophe.copyElement(elem);
```

to

```
var newElem = (typeof xmlGen.importNode === 'function') ? xmlGen.importNode(elem, true) : Strophe.copyElement(elem);
```

**Comment by evenisse** [comment] 2011-03-21 23:08
I'm agree with becoded. This code fix the issue and work on all browsers

**Comment by dtabuenc** [comment] 2011-03-30 15:39
Has someone submitted a pull request for becoded's sugestion? I had to do this for it to work on my IE8 + Windows 7 since for some reason doing xmlGen.importNode ? or even xmlGen['importNode'] both trigger a a call to importNode with 0 params. Gotta love IE.

**Comment by brendon-codes** [comment] 2011-04-24 02:49
Hey guys, I made a pull request for this. After looking again through the comments, I realized thaBongo had the same solution as me, which is the correct fix for this IMO. The pull request is here:

https://github.com/metajack/strophejs/pull/44

**Comment by astro** [comment] 2011-11-14 00:42
Pull request #44 has been merged.

**Closed as completed by astro** 2011-11-14 00:42 UTC
